AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    # Because this below isn't under my control. toad.
    - app/admin/**/*
    - app/mailers/**/*
  RunRailsCops: true
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
